[package]
name = "osd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.15.5"
gdk = "0.15.4"
cairo-rs = "0.15.11"
glib = "0.15.11"